### ISSUE TITLE
[question] OS compatibility of release binaries

### ISSUE THREAD

**Issue by timosachsenberg** [UWPR/Comet#32]
Hi,
Just to confirm: are the release binaries build with the same GitHub runner as in the actions? 
e.g. thus probably only supported in recent versions of linux, macos, ...?
Best,
Timo

**Comment by timosachsenberg** [comment]
Thanks for your quick answer and your continued work on comet!

Just for consideration (we can of course build it ourselves): using the oldest (e.g. ideally, “deprecated”) runner version for releases could mean that users that deploy comet in, e.g., a docker container with other tools don't need to bump their base images up, etc. Just a tiny bit more convenient.

Or building it in a container (e.g., some older debian manylinux2014) but a bit more involved.

Anyway, :) not super important - just wanted to share my thoughts.

**Comment by jke000** [comment]
Tim, that's something I haven't even considered since Comet migrated to GitHub with the release binaries built by the actions.  But I'm all for making things more convenient and this change makes sense to me.  The two deprecated runners, "macos-10.15" and "ubuntu-18.04", go away in May and December so swapping to those wouldn't make sense given the short term fix; I'm not even sure that there will be another release by May.  I will change the runners to "macos-11" and "ubuntu-20.04" though.  But if those aren't sufficiently old enough to address some large swath of this issue, I'm happy to work with you or anyone else willing to put more effort into addressing this (as I don't think I'm up to tackling the "bit more involved" work at this stage!).
