### ISSUE TITLE
deltaCN always 1

### ISSUE THREAD

**Issue by jonasscheid** [UWPR/Comet#33]
Hey!
I ran immunopeptidomics data with comet and took a deeper look into what comet gives out. Turns out, that in the pep.xml the deltaCN values are always 1. However, in the pin file (from the same run) I see a nice distribution of deltaCN values.

Here are the parameters I used to run comet:
[param.txt](https://github.com/UWPR/Comet/files/10981297/param.txt)

Can you reproduce this with some internal data of yours?

**Comment by jke000** [comment]
Thanks for reporting this.  And yes, I can reproduce what you see.  This behavior of deltaCn always being "1" when "num_output_lines = 1" in pep.xml output has been this way since original 2012 Comet.  The Percolator pin output came later and I addressed this issue for that output but that small code change never made it back to the pep.xml output.  I'll make a minor release today that addresses this issue.
