### ISSUE TITLE
Installation under WSL

### ISSUE THREAD

**Issue by JannikSchneider12** [UWPR/Comet#48]
Hey,

I wanted to install comet on wsl but have problems to make it run. I tried downloading the precompiled version and I also tried to download the sourcecode and compile with "make". In both cases this is the result:

(peptideidentification) jannik@DELLXPS:~/comet/Comet-2023.01.2$ mono ./comet.exe -h
Cannot open assembly './comet.exe': File does not contain a valid CIL image.

Does someone has an idea what could be the reason?

Thanks for your time and help

**Comment by jke000** [comment]
Get rid of the mono command ... what happens when you run the binary directly e.g. `./comet.exe -h`?  I downloaded both comet.win64.exe and comet.linux.exe from the last release and can run both directly under WSL Ubuntu.  fwiw, the win64 binary was a bit faster (30 seconds vs 42 seconds) compared to the linux binary in my test search in WSL Ubuntu.

**Comment by JannikSchneider12** [comment]
Thank you very much. Now it worked without any problems, so mono seems to be the problem. 

I have another question regarding the output and also percolator. Do I see it right that I just have to set the decoy search parameter to 1 as well as the output_percolatorfile parameter? Because I know from other search engines that sometimes one has to perform seperate searches with a target-only and then decoy-only file in order to have a valid pin file for percolator.

Thanks again for your time and help

**Comment by jke000** [comment]
If you are using a sequence database without decoy entries in it (i.e. your FASTA file does not have target and decoy sequences) then you would set `decoy_search = 1` and `output_percolatorfile = 1` in the parameters.  These two parameters direct Comet to generate [pseudo-reverse decoy peptides](https://uwpr.github.io/Comet/notes/20190314_decoys.html) and export a .pin file that can be fed to Percolator.  If you are a target-decoy FASTA file, and thus not using Comet's internal decoys, then set `decoy_search = 0` and make sure to set `decoy_prefix = XYZ` where XYZ is the prefix string of your decoy entries (possibly something like "rev_" or "decoy_").  The `decoy_prefix` parameter is used by Comet to know which of the sequences in the FASTA are target sequences vs. decoy sequences so that those can be properly annotated in the Percolator .pin file.

You can do separate target-only and decoy-only searches if you really want to but that's definitely not required to generate a valid pin file and it's something that I personally never do with Comet searches.
